### ISSUE TITLE
Missing quotes leading to EOF Error

### ISSUE THREAD

**Issue by emk3y** [splunk/pytest-splunk-addon#192]
In File `pytest_splunk_addon/helmut/__init__.py` there are triple opening quotes, but no closing quotes. This leads to an `SyntaxError: EOF while scanning triple-quoted string literal`.

**Comment by bhargav-nariyani-crest** [comment]
This should be fixed as a part of the next release.

**Comment by monishshah-crest** [comment]
Issue has been fixed by this PR https://github.com/splunk/pytest-splunk-addon/pull/190 Hence, Closing this.
