### ISSUE TITLE
Difference between splunk-appinspect vs pytest-splunk-addon

### ISSUE THREAD

**Issue by getkub** [splunk/pytest-splunk-addon#370]
**Feature Request**
Do you have a simple comparison page/document to show 
- the similarities between  pytest-splunk-addon &  splunk-appinspect 
- The difference between pytest-splunk-addon &  splunk-appinspect 

To provide management with ability to choose pytest-splunk-addon over splunk-appinspect as the appinspect have quite a few errors

**Comment by rfaircloth-splunk** [comment]
the comparisson is apples and chicken. Both testing tools but different things. appinspect is "things you should not do" but pytest-splunk-addon is validation you did things you should. (add-on works). An add-on could work but break a rule for cloud so both tools have their own value we use both extensivly internally
