### ISSUE TITLE
Documentation links and formatting

### ISSUE THREAD

**Issue by jaydeluca** [splunk/pytest-splunk-addon#834]
While reading the documentation, I have been encountering what looks like what might be broken links or references, where there is a `{ref}` followed by what looks like should be a hyperlink of some sort

Example:
```
The conf file should follow the specifications as mentioned {ref}`here <conf_spec`.
```

Examples in code base:
* https://github.com/splunk/pytest-splunk-addon/blob/b789bb480e590c8182b94f35548ec4bcf7b3c263/docs/how_to_use.md?plain=1#L249
* https://github.com/splunk/pytest-splunk-addon/blob/b789bb480e590c8182b94f35548ec4bcf7b3c263/docs/index_time_tests.md?plain=1#L17
* https://github.com/splunk/pytest-splunk-addon/blob/b789bb480e590c8182b94f35548ec4bcf7b3c263/docs/index_time_tests.md?plain=1#L75

When rendered on the doc site they look like:

<img width="746" alt="image" src="https://github.com/splunk/pytest-splunk-addon/assets/7630696/e975dc12-e999-4ed8-b21f-7a48fa0ccda3">

<img width="828" alt="image" src="https://github.com/splunk/pytest-splunk-addon/assets/7630696/b204204f-7758-4c2b-9779-05d09497c5ab">

<img width="550" alt="image" src="https://github.com/splunk/pytest-splunk-addon/assets/7630696/5b03a06c-c57f-401e-ad3f-a0610c105ca3">

Should these be linking to something or formatting differently?

Also, anywhere there is an example cli argument, there is usually a placeholder explaining what the value should be, but they are all missing a closing `>`. 

Example: 
https://github.com/splunk/pytest-splunk-addon/blob/b789bb480e590c8182b94f35548ec4bcf7b3c263/docs/how_to_use.md?plain=1#L23

Should these instead be closed like below or is this intentional?

 ```bash
 pytest --splunk-type=external --splunk-app=<path-to-addon-package> --splunk-data-generator=<path to pytest-splunk-addon-data.conf file> --splunk-host=<hostname> --splunk-port=<splunk-management-port> --splunk-user=<username> --splunk-password=<password> --splunk-hec-token=<splunk_hec_token>
 ```

**Comment by artemrys** [comment]
@jaydeluca thanks for raising the ticket, we just recently migrated documentation to GitHub Pages and something might look wrong

we will work on the necessary fixes
